# These rules inject env vars into the k8scontrol function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: k8scontrol-generated-secrets-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
- source:
    objref:
      name: combined-target-secrets
    fieldref: ".secretGroups.[name=targetSshSecrets].values.[name=publicKey].data"
  target:
    objref:
      kind: KubeadmControlPlane
      name: cluster-controlplane
    fieldrefs:
      - "spec.kubeadmConfigSpec.users[name=deployer].sshAuthorizedKeys[0]%REPLACE_HOST_SSH_KEY%"
