apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../type/gating/shared/catalogues
  - hosts.yaml
  - networking-ha.yaml

patchesStrategicMerge:
  - versions-airshipctl.yaml
  - networking.yaml
