apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/crd
- upstream/manager
patchesStrategicMerge:
- deployment_toleration_patch.yaml
- deployment_proxyvar_patch.yaml
