apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/baremetal-operator
  - ../../../../function/hwcc
  - ../../../../function/clusterctl

commonLabels:
  airshipit.org/stage: initinfra
