apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: tigera-operator-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.images.tigera_operator.tigera_operator.repository.image}"
  target:
    objref:
      kind: Deployment
      name: tigera-operator
    fieldrefs: ["{.spec.template.spec.containers[?(.name == 'tigera-operator')].image}"]
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.image_repositories.cni.repository}"
  target:
    objref:
      kind: Installation
      name: default
    fieldrefs: ["{.spec.registry}"]
