apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../catalogues
  - ../../../../composite/infra
commonLabels:
  airshipit.org/stage: initinfra

transformers:
  - ../../../../composite/infra/replacements
