apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kubeadmconfigtemplate.yaml
  - metal3machinetemplate.yaml
  - machinedeployment.yaml

namespace: target-infra
