# These rules inject versioned artifacts into the ephemeral function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: ephemeral-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
# Replace the imageRepository in the KubeadmEphemeral
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.image_repositories.controlplane.repository}"
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_IMAGE_REPOSITORY%"]
