# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The validation config should be defined as part of appropriate "Phase" or "Plan" kind (config.validation field)
apiVersion: airshipit.org/v1alpha1
kind: Phase
metadata:
  name: phase-name
config:
  validation:
    # Disallow additional properties not in schema - default "true"
    strict: true
    # Version of Kubernetes to validate against - default "1.18.6"
    kubernetesVersion: "1.18.6"
    # Skip validation for resource definitions without a schema - default "false"
    ignoreMissingSchemas: false
    # List of kind names to skip from validation
    kindsToSkip:
      - Clusterctl
      - VariableCatalogue
    # list of kustomize entrypoints located in "TARGET_PATH" with additional CRDs
    crdList:
      - airshipctl/manifests/function/airshipctl-schemas
  documentEntryPoint: ephemeral/initinfra
